### ISSUE TITLE
Видео Angular митапов?

### ISSUE THREAD

**Issue by splincode** [hH39797J/javascript-videos-ru-2018#11]

**Comment by hH39797J** [comment]
Добрый вечер.

Поделитесь, пожалуйста, ссылками на Angular митапы - добавлю.

**Comment by splincode** [comment]
https://github.com/Angular-RU/angular-russia-meetups

**Comment by hH39797J** [comment]
В 2018 был только 1 митап - https://www.meetup.com/AngularMoscow/events/247377723/

Похоже, что видео ещё не появилось.

**Comment by hH39797J** [comment]
Добавлять, в данный момент, нечего.

Спасибо за участие.
