### ISSUE TITLE
Frontend fwdays

### ISSUE THREAD

**Issue by ana-ya** [hH39797J/javascript-videos-ru-2018#15]
A new update will be on 18 March 2018 - https://www.youtube.com/channel/UC3NDbeN0Jq_InNAhiJtvHcQ

**Comment by hH39797J** [comment]
Добрый день.

Я не смог найти видео за 2018 год по вашей ссылке.
Добавлять, в данный момент, нечего.

Спасибо за участие.

**Comment by ana-ya** [comment]
Я написала когда будут обновления - 18 марта и тогда можно будет сразу свежее добавить

**Comment by hH39797J** [comment]
Да, хорошо.

Когда будут видео, тогда и откроем issue.

Спасибо за участие.

**Comment by hH39797J** [comment]
https://fwdays.com/en/event/js-fwdays-2018
18 марта 2018
https://www.youtube.com/playlist?list=PLPcgQFk9n9y8_G0Gyh0yqDuiZqy15RLDo

**Comment by hH39797J** [comment]
Готово (Track A).
https://github.com/hH39797J/javascript-videos-ru-2018#javascript-fwdays18

**Comment by hH39797J** [comment]
Готово (Track B).
https://github.com/hH39797J/javascript-videos-ru-2018#javascript-fwdays18

**Comment by hH39797J** [comment]
Готово (Tech talks).
https://github.com/hH39797J/javascript-videos-ru-2018#javascript-fwdays18
