### ISSUE TITLE
Intro React - Open lectures

### ISSUE THREAD

**Issue by ana-ya** [hH39797J/javascript-videos-ru-2018#16]
The lectures were created by Illia Klimov https://www.youtube.com/watch?v=e_KLk92LLvU&list=PLvTBThJr861xh3fCMf91Ip5_r6TdR15O9

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/javascript-videos-ru-2018#%D0%A3%D1%87%D0%B5%D0%B1%D0%BD%D1%8B%D0%B5-%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8B
