### ISSUE TITLE
Пятиминутка Angular

### ISSUE THREAD

**Issue by ana-ya** [hH39797J/javascript-videos-ru-2018#18]
Новости из мира Angular (Алексей Охрименко). Регулярные выпуски: 
 https://www.youtube.com/channel/UCQGzS3MitYnnjTRn2vanOmg

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/javascript-videos-ru-2018#%D0%9F%D0%BE%D0%B4%D0%BA%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B3
