### ISSUE TITLE
Krasnodar Frontend

### ISSUE THREAD

**Issue by langovoi** [hH39797J/javascript-videos-ru-2018#45]
[Krasnodar Frontend: Meetup #2](https://krddevdays.timepad.ru/event/634499/) ([видео](https://www.youtube.com/watch?v=FVJqLtW5MAw&list=PL1irPRp3Ng9bQei9ohczfBOis6yFgyKT_))
[Krasnodar Frontend: Meetup #3](https://krddevdays.timepad.ru/event/717194/) ([видео](https://www.youtube.com/watch?v=Lvuv4SlTDXo&list=PL1irPRp3Ng9Z3WZpvK7lBZtYEzUvMAyLy))

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/javascript-videos-ru-2018#krasnodar-frontend-meetup-3

**Comment by hH39797J** [comment]
Готово.
https://github.com/hH39797J/javascript-videos-ru-2018#krasnodar-frontend-meetup-2
