### ISSUE TITLE
Видео с RS Conf 2018

### ISSUE THREAD

**Issue by askd** [hH39797J/javascript-videos-ru-2018#9]
Добрый день! Почему некоторые видео с RS Conf 2018 отсутствуют?

**Comment by hH39797J** [comment]
Добрый день.

Я добавил все доступные видео из [RSconf2018 youtube playlists](https://www.youtube.com/playlist?list=PLe--kalBDwjgH1MQpttWyHmDR98Q404Tn) ссылка на которые находится на https://2018.conf.rollingscopes.com/index.html

Меня тоже сильно удивил тот факт, что некоторые видео отсутствуют.

Я обновлю свои записи, если недостающие видео добавятся.

**Comment by askd** [comment]
Спасибо! Сообщу организаторам

**Comment by hH39797J** [comment]
Я обновил свои записи, т.к. появилось 2 недостающих видео из 4-х.

**Comment by askd** [comment]
Спасибо! С оставшимися двумя, судя по словам организаторов, возникли проблемы.
